enum UsersEnumType {
  CREATE_USER = "CREATE_USER",
  EDIT_USER = "EDIT_USER",
  DELETE_USER = "DELETE_USER",
  UPDATED_EMAIL = "UPDATED_EMAIL",
  UPDATED_PASSWORD = "UPDATED_PASSWORD",
  UPDATED_ROLE = "UPDATED_ROLE",
  UPDATED_NAME = "UPDATED_NAME",
}

export { UsersEnumType };
